### ISSUE TITLE
Cross talk

### ISSUE THREAD

**Issue by krishnak** [glenn20/micropython-espnow-images#31]
Micropython ESPNOW running on ESP32 built from source g20-dev

Receiver is on SOFTAP mode listening on Channel 5

Tx is on Channel 4 - 10% Transmission reaches receiver 
Tx is on Channel 6 - 10% Transmission reaches receiver

This happens only for these two adjacent channels, I feel it is the underlying Radio which is causing it. I am just raising it for reference

**Comment by glenn20** [comment]
Thanks for the report. I believe this may be a normal consequence of the esp32 devices using HT40 mode by default (ie, they communicate across two channels - 40MHz bandwidth). On the other hand it could also be real cross-talk across 20MHz channels, but I haven't seen instances of that myself.

It is possible to turn off the secondary channel using `esp_wifi_set_channel(5, WIFI_SECOND_CHAN_NONE)` but that is not possible with micropython.

I proposed a PR to allow that, but was rejected. It only affects espnow communication (as APs negotiate HT40/HT20 with the device).

If this is a significent issue for you (or others), I could provide a mechanism to enforce HT20 mode in the espnow module, otherwise I'll close this as won't/can't fix ;).

**Comment by krishnak** [comment]
the cross talk is appearing consistently on the device has both STA+AP enabled (which is inline with your observation) and the STA is connected to the internet via router and the AP is purely for ESP NOW . This device finds packets on both the adjacent channels say 10-30% of the time. However when it sends back an ESP NOW acknowledgement data on the incorrect channel - the ESP Now node which sent it is not receiving it (as expected)

**Comment by krishnak** [comment]
You can ignore this request and close
